import pandas as pd
import numpy as np
import pvlib
from typing import List, Dict, Any

def resample_with_interpolation(df, target_freq, sim_end: float | None = None, var_type: str = 'extensive'):
    """
    Resample a time series DataFrame to a new frequency, 
    handling both upsampling (with interpolation) and 
    downsampling (with aggregation).

    Parameters
    ----------
    df : pandas.DataFrame
        Input DataFrame with a DatetimeIndex.
    target_freq : str
        New frequency (e.g., "15T", "1H", "1D").
    agg : str or callable, default="mean"
        Aggregation method for downsampling (e.g., "mean", "sum").

    Returns
    -------
    pandas.DataFrame
        Resampled DataFrame.
    NOTE_: generated by ChatGPT
    """
    if not isinstance(df.index, pd.DatetimeIndex):
        raise ValueError("DataFrame must have a DatetimeIndex.")
    
    # Check if repetition is needed
    if sim_end is not None:
        period = df.index[-1] - df.index[0] + (df.index[1] - df.index[0])
        n_repeat = int(np.ceil((pd.to_timedelta(sim_end, 's')) / period))
        dfs = []
        for i in range(n_repeat):
            df_copy = df.copy()
            df_copy.index = df_copy.index + i * period
            dfs.append(df_copy)
        df = pd.concat(dfs)
        # Trim to exact simulation end
        df = df[df.index <= df.index[0] + pd.to_timedelta(sim_end, 's')]
    # Check original resolution
    original_freq = pd.infer_freq(df.index)
    if original_freq is None:
        # If infer_freq fails, approximate from median diff
        original_step = df.index.to_series().diff().median()
    else:
        original_step = pd.to_timedelta(pd.tseries.frequencies.to_offset(original_freq))
    # Adding one line to prevent the final dataframe being too short
    if isinstance(df, pd.DataFrame):
        df.loc[df.index[-1] + original_step, :] = df.loc[df.index[-1], :]
    elif isinstance(df, pd.Series):
        df.loc[df.index[-1] + original_step] = df.loc[df.index[-1]]
    target_step = pd.to_timedelta(pd.tseries.frequencies.to_offset(target_freq))

    if target_step >= original_step: # --- Downsampling ---
        match var_type:
            case 'extensive':
                output = df.resample(target_freq).agg('sum').to_numpy()
            case 'intensive':
                output = df.resample(target_freq).agg('mean').to_numpy()
    else:  # --- Upsampling ---
        match var_type:
            case 'extensive':
                output = df.resample(target_freq).ffill()
                output = output * (target_step / original_step)
                output = output.to_numpy()
            case 'intensive':
                output = df.reindex(pd.date_range(df.index[0], df.index[-1], freq = target_freq, tz=df.index.tz))
                output = output.interpolate(method='time').to_numpy()
    return output.ravel()


def C2K(T):
    """
    Convert temperature from Celsius to Kelvin.
    
    Parameters
    ----------
    T : float, int, list, or np.ndarray
        Temperature value(s) in Celsius.
    
    Returns
    -------
    float, int, list, or np.ndarray
        Temperature in Kelvin, preserving the input type.
        
    Examples
    --------
    >>> C2K(0)
    273.15
    >>> C2K([0, 25, 100])
    [273.15, 298.15, 373.15]
    >>> C2K(np.array([0, 25]))
    array([273.15, 298.15])
    """
    if isinstance(T, list):
        result = np.asarray(T) + 273.15
        return result.tolist()
    else:
        return T + 273.15


def K2C(T):
    """
    Convert temperature from Kelvin to Celsius.
    
    Parameters
    ----------
    T : float, int, list, or np.ndarray
        Temperature value(s) in Kelvin.
    
    Returns
    -------
    float, int, list, or np.ndarray
        Temperature in Celsius, preserving the input type.
        
    Examples
    --------
    >>> K2C(273.15)
    0.0
    >>> K2C([273.15, 298.15, 373.15])
    [0.0, 25.0, 100.0]
    >>> K2C(np.array([273.15, 298.15]))
    array([0., 25.])
    """
    if isinstance(T, list):
        result = np.asarray(T) - 273.15
        return result.tolist()
    else:
        return T - 273.15

def find_object_of_type(object_type: Any, object_pool: List[Any] | Dict[str, Any]) -> Any:
    """
    Finds and returns the first component of the specified type in the list of components.

    Args:
        object_type (Object): The type of component to search for.
        object_pool (List[Object] or Dict[str, Object]): The list (or dict) of objects to search through.

    Returns:
        Object: The first object found of the specified type. Returns None if nothing is found

    """
    if isinstance(object_pool, dict):
        object_pool = [v for k, v in object_pool.items()]
    for object in object_pool:
        if isinstance(object, object_type):
            return object
    return None

def check_datetime_index(df: pd.DataFrame):
        if not isinstance(df.index, pd.DatetimeIndex):
            raise ValueError("DataFrame index must be a DatetimeIndex")
        

def calculate_solar_angles(latitude: float, longitude: float, timestamps: pd.DatetimeIndex):
    """
    Calculate solar zenith and azimuth for a location and timestamps.

    Parameters
    ----------
    latitude : float
        Latitude in degrees (positive north)
    longitude : float
        Longitude in degrees (positive east)
    timestamps : pd.DatetimeIndex
        Times for which to compute solar positions (timezone-aware is preferred)

    Returns
    -------
    zenith : pd.Series
        Solar zenith angle in degrees
    azimuth : pd.Series
        Solar azimuth angle in degrees
    """
    # Assume UTC if no timezone
    if timestamps.tz is None:
        timestamps = timestamps.tz_localize('UTC')
    
    solpos = pvlib.solarposition.get_solarposition(
        time=timestamps,
        latitude=latitude,
        longitude=longitude
    )

    zenith = solpos['zenith']
    azimuth = solpos['azimuth']

    return zenith, azimuth


class NodeImbalanceError(Exception):
    pass

class StorageError(Exception):
    pass

class OnOffComponentError(BaseException):
    pass
